///scr_createNavigation()

//---Create navigation---
//define navigation data as a ds grid. Columns are name, followed by the 5 options
global.navigation = ds_grid_create(6,133);

//populate inventory

//-----------------------------------------------------------//
//-----------------------HOME--------------------------------//
//-----------------------------------------------------------//

//---Interior--//
ds_grid_set(global.navigation, 0,  0, "homeInteriorChoices");
ds_grid_set(global.navigation, 1,  0, "Go to the door");
ds_grid_set(global.navigation, 2,  0, "Go to the window");
ds_grid_set(global.navigation, 3,  0, "Go to bed");
ds_grid_set(global.navigation, 4,  0, "NOTHING");
ds_grid_set(global.navigation, 5,  0, "NOTHING");
ds_grid_set(global.navigation, 0,  1, "homeInteriorTargets");
ds_grid_set(global.navigation, 1,  1, "homeLockedDoor");
ds_grid_set(global.navigation, 2,  1, "homeWindow");
ds_grid_set(global.navigation, 3,  1, "homeBed");
ds_grid_set(global.navigation, 4,  1, "NOTHING");
ds_grid_set(global.navigation, 5,  1, "NOTHING");
ds_grid_set(global.navigation, 0,  2, "homeInteriorInventoryGet");
ds_grid_set(global.navigation, 1,  2, "NOTHING");
ds_grid_set(global.navigation, 2,  2, "NOTHING");
ds_grid_set(global.navigation, 3,  2, "Favourite Bone");
ds_grid_set(global.navigation, 4,  2, "NOTHING");
ds_grid_set(global.navigation, 5,  2, "NOTHING");
ds_grid_set(global.navigation, 0,  3, "homeInteriorInventoryNeed");
ds_grid_set(global.navigation, 1,  3, "NOTHING");
ds_grid_set(global.navigation, 2,  3, "NOTHING");
ds_grid_set(global.navigation, 3,  3, "NOTHING");
ds_grid_set(global.navigation, 4,  3, "NOTHING");
ds_grid_set(global.navigation, 5,  3, "NOTHING");
ds_grid_set(global.navigation, 0,  4, "homeInteriorInventoryMissingTarget");
ds_grid_set(global.navigation, 1,  4, "NOTHING");
ds_grid_set(global.navigation, 2,  4, "NOTHING");
ds_grid_set(global.navigation, 3,  4, "NOTHING");
ds_grid_set(global.navigation, 4,  4, "NOTHING");
ds_grid_set(global.navigation, 5,  4, "NOTHING");
ds_grid_set(global.navigation, 0,  5, "homeInteriorInventoryDestroy");
ds_grid_set(global.navigation, 1,  5, "NOTHING");
ds_grid_set(global.navigation, 2,  5, "NOTHING");
ds_grid_set(global.navigation, 3,  5, "NOTHING");
ds_grid_set(global.navigation, 4,  5, "NOTHING");
ds_grid_set(global.navigation, 5,  5, "NOTHING");

//---LockedDoor--//
ds_grid_set(global.navigation, 0,  6, "homeLockedDoorChoices");
ds_grid_set(global.navigation, 1,  6, "Go to the window");
ds_grid_set(global.navigation, 2,  6, "Go to bed");
ds_grid_set(global.navigation, 3,  6, "NOTHING");
ds_grid_set(global.navigation, 4,  6, "NOTHING");
ds_grid_set(global.navigation, 5,  6, "NOTHING");
ds_grid_set(global.navigation, 0,  7, "homeLockedDoorTargets");
ds_grid_set(global.navigation, 1,  7, "homeWindow");
ds_grid_set(global.navigation, 2,  7, "homeBed");
ds_grid_set(global.navigation, 3,  7, "NOTHING");
ds_grid_set(global.navigation, 4,  7, "NOTHING");
ds_grid_set(global.navigation, 5,  7, "NOTHING");
ds_grid_set(global.navigation, 0,  8, "homeLockedDoorInventoryGet");
ds_grid_set(global.navigation, 1,  8, "NOTHING");
ds_grid_set(global.navigation, 2,  8, "Favourite Bone");
ds_grid_set(global.navigation, 3,  8, "NOTHING");
ds_grid_set(global.navigation, 4,  8, "NOTHING");
ds_grid_set(global.navigation, 5,  8, "NOTHING");
ds_grid_set(global.navigation, 0,  9, "homeLockedDoorInventoryNeed");
ds_grid_set(global.navigation, 1,  9, "NOTHING");
ds_grid_set(global.navigation, 2,  9, "NOTHING");
ds_grid_set(global.navigation, 3,  9, "NOTHING");
ds_grid_set(global.navigation, 4,  9, "NOTHING");
ds_grid_set(global.navigation, 5,  9, "NOTHING");
ds_grid_set(global.navigation, 0,  10, "homeLockedDoorInventoryMissingTarget");
ds_grid_set(global.navigation, 1,  10, "NOTHING");
ds_grid_set(global.navigation, 2,  10, "NOTHING");
ds_grid_set(global.navigation, 3,  10, "NOTHING");
ds_grid_set(global.navigation, 4,  10, "NOTHING");
ds_grid_set(global.navigation, 5,  10, "NOTHING");
ds_grid_set(global.navigation, 0,  11, "homeLockedDoorInventoryDestroy");
ds_grid_set(global.navigation, 1,  11, "NOTHING");
ds_grid_set(global.navigation, 2,  11, "NOTHING");
ds_grid_set(global.navigation, 3,  11, "NOTHING");
ds_grid_set(global.navigation, 4,  11, "NOTHING");
ds_grid_set(global.navigation, 5,  11, "NOTHING");

//---Window--//
ds_grid_set(global.navigation, 0,  12, "homeWindowChoices");
ds_grid_set(global.navigation, 1,  12, "Jump through the window");
ds_grid_set(global.navigation, 2,  12, "Go to the door");
ds_grid_set(global.navigation, 3,  12, "Go to bed");
ds_grid_set(global.navigation, 4,  12, "NOTHING");
ds_grid_set(global.navigation, 5,  12, "NOTHING");
ds_grid_set(global.navigation, 0,  13, "homeWindowTargets");
ds_grid_set(global.navigation, 1,  13, "exterior");
ds_grid_set(global.navigation, 2,  13, "homeLockedDoor");
ds_grid_set(global.navigation, 3,  13, "homeBed");
ds_grid_set(global.navigation, 4,  13, "NOTHING");
ds_grid_set(global.navigation, 5,  13, "NOTHING");
ds_grid_set(global.navigation, 0,  14, "homeWindowInventoryGet");
ds_grid_set(global.navigation, 1,  14, "NOTHING");
ds_grid_set(global.navigation, 2,  14, "NOTHING");
ds_grid_set(global.navigation, 3,  14, "Favourite Bone");
ds_grid_set(global.navigation, 4,  14, "NOTHING");
ds_grid_set(global.navigation, 5,  14, "NOTHING");
ds_grid_set(global.navigation, 0,  15, "homeWindowInventoryNeed");
ds_grid_set(global.navigation, 1,  15, "NOTHING");
ds_grid_set(global.navigation, 2,  15, "NOTHING");
ds_grid_set(global.navigation, 3,  15, "NOTHING");
ds_grid_set(global.navigation, 4,  15, "NOTHING");
ds_grid_set(global.navigation, 5,  15, "NOTHING");
ds_grid_set(global.navigation, 0,  16, "homeWindowInventoryMissingTarget");
ds_grid_set(global.navigation, 1,  16, "NOTHING");
ds_grid_set(global.navigation, 2,  16, "NOTHING");
ds_grid_set(global.navigation, 3,  16, "NOTHING");
ds_grid_set(global.navigation, 4,  16, "NOTHING");
ds_grid_set(global.navigation, 5,  16, "NOTHING");
ds_grid_set(global.navigation, 0,  17, "homeWindowInventoryDestroy");
ds_grid_set(global.navigation, 1,  17, "NOTHING");
ds_grid_set(global.navigation, 2,  17, "NOTHING");
ds_grid_set(global.navigation, 3,  17, "NOTHING");
ds_grid_set(global.navigation, 4,  17, "NOTHING");
ds_grid_set(global.navigation, 5,  17, "NOTHING");

//---Bed--//
ds_grid_set(global.navigation, 0,  18, "homeBedChoices");
ds_grid_set(global.navigation, 1,  18, "Go to the door");
ds_grid_set(global.navigation, 2,  18, "Go to the window");
ds_grid_set(global.navigation, 3,  18, "NOTHING");
ds_grid_set(global.navigation, 4,  18, "NOTHING");
ds_grid_set(global.navigation, 5,  18, "NOTHING");
ds_grid_set(global.navigation, 0,  19, "homeBedTargets");
ds_grid_set(global.navigation, 1,  19, "homeLockedDoor");
ds_grid_set(global.navigation, 2,  19, "homeWindow");
ds_grid_set(global.navigation, 3,  19, "NOTHING");
ds_grid_set(global.navigation, 4,  19, "NOTHING");
ds_grid_set(global.navigation, 5,  19, "NOTHING");
ds_grid_set(global.navigation, 0,  20, "homeBedInventoryGet");
ds_grid_set(global.navigation, 1,  20, "NOTHING");
ds_grid_set(global.navigation, 2,  20, "NOTHING");
ds_grid_set(global.navigation, 3,  20, "NOTHING");
ds_grid_set(global.navigation, 4,  20, "NOTHING");
ds_grid_set(global.navigation, 5,  20, "NOTHING");
ds_grid_set(global.navigation, 0,  21, "homeBedInventoryNeed");
ds_grid_set(global.navigation, 1,  21, "NOTHING");
ds_grid_set(global.navigation, 2,  21, "NOTHING");
ds_grid_set(global.navigation, 3,  21, "NOTHING");
ds_grid_set(global.navigation, 4,  21, "NOTHING");
ds_grid_set(global.navigation, 5,  21, "NOTHING");
ds_grid_set(global.navigation, 0,  22, "homeBedInventoryMissingTarget");
ds_grid_set(global.navigation, 1,  22, "NOTHING");
ds_grid_set(global.navigation, 2,  22, "NOTHING");
ds_grid_set(global.navigation, 3,  22, "NOTHING");
ds_grid_set(global.navigation, 4,  22, "NOTHING");
ds_grid_set(global.navigation, 5,  22, "NOTHING");
ds_grid_set(global.navigation, 0,  23, "homeBedInventoryDestroy");
ds_grid_set(global.navigation, 1,  23, "NOTHING");
ds_grid_set(global.navigation, 2,  23, "NOTHING");
ds_grid_set(global.navigation, 3,  23, "NOTHING");
ds_grid_set(global.navigation, 4,  23, "NOTHING");
ds_grid_set(global.navigation, 5,  23, "NOTHING");


//-----------------------------------------------------------//
//---------------------Exterior------------------------------//
//-----------------------------------------------------------//

//---Exterior--//
ds_grid_set(global.navigation, 0,  24, "exteriorChoices");
ds_grid_set(global.navigation, 1,  24, "Go to the wood");
ds_grid_set(global.navigation, 2,  24, "Go to the empty house");
ds_grid_set(global.navigation, 3,  24, "Go to the abandoned shop");
ds_grid_set(global.navigation, 4,  24, "Go to the old woman's yard");
ds_grid_set(global.navigation, 5,  24, "Go home");
ds_grid_set(global.navigation, 0,  25, "exteriorTargets");
ds_grid_set(global.navigation, 1,  25, "woodInterior");
ds_grid_set(global.navigation, 2,  25, "emptyHouseInterior");
ds_grid_set(global.navigation, 3,  25, "abandonedShopInterior");
ds_grid_set(global.navigation, 4,  25, "yardInterior");
ds_grid_set(global.navigation, 5,  25, "homeInterior");
ds_grid_set(global.navigation, 0,  26, "exteriorInventoryGet");
ds_grid_set(global.navigation, 1,  26, "NOTHING");
ds_grid_set(global.navigation, 2,  26, "NOTHING");
ds_grid_set(global.navigation, 3,  26, "NOTHING");
ds_grid_set(global.navigation, 4,  26, "Open Dog Food");
ds_grid_set(global.navigation, 5,  26, "NOTHING");
ds_grid_set(global.navigation, 0,  27, "exteriorInventoryNeed");
ds_grid_set(global.navigation, 1,  27, "NOTHING");
ds_grid_set(global.navigation, 2,  27, "Collar");
ds_grid_set(global.navigation, 3,  27, "NOTHING");
ds_grid_set(global.navigation, 4,  27, "Dog Food");
ds_grid_set(global.navigation, 5,  27, "NOTHING");
ds_grid_set(global.navigation, 0,  28, "exteriorInventoryMissingTarget");
ds_grid_set(global.navigation, 1,  28, "NOTHING");
ds_grid_set(global.navigation, 2,  28, "missingCollar");
ds_grid_set(global.navigation, 3,  28, "NOTHING");
ds_grid_set(global.navigation, 4,  28, "missingDogFood");
ds_grid_set(global.navigation, 5,  28, "NOTHING");
ds_grid_set(global.navigation, 0,  29, "exteriorInventoryDestroy");
ds_grid_set(global.navigation, 1,  29, "NOTHING");
ds_grid_set(global.navigation, 2,  29, "Collar");
ds_grid_set(global.navigation, 3,  29, "NOTHING");
ds_grid_set(global.navigation, 4,  29, "Dog Food");
ds_grid_set(global.navigation, 5,  29, "NOTHING");




//-----------------------------------------------------------//
//-----------------------Wood--------------------------------//
//-----------------------------------------------------------//

//--woodInterior--//
ds_grid_set(global.navigation, 0, 30, "woodInteriorChoices" );
ds_grid_set(global.navigation, 1, 30, "Explore the wood" );
ds_grid_set(global.navigation, 2, 30, "Go to the den" );
ds_grid_set(global.navigation, 3, 30, "Leave the wood" );
ds_grid_set(global.navigation, 4, 30, "NOTHING" );
ds_grid_set(global.navigation, 5, 30, "NOTHING" );
ds_grid_set(global.navigation, 0, 31, "woodInteriorTargets" );
ds_grid_set(global.navigation, 1, 31, "woodExplore" );
ds_grid_set(global.navigation, 2, 31, "woodDen" );
ds_grid_set(global.navigation, 3, 31, "exterior" );
ds_grid_set(global.navigation, 4, 31, "NOTHING" );
ds_grid_set(global.navigation, 5, 31, "NOTHING" );
ds_grid_set(global.navigation, 0, 32, "woodInteriorInventoryGet" );
ds_grid_set(global.navigation, 1, 32, "Stick" );
ds_grid_set(global.navigation, 2, 32, "Dog Food" );
ds_grid_set(global.navigation, 3, 32, "NOTHING" );
ds_grid_set(global.navigation, 4, 32, "NOTHING" );
ds_grid_set(global.navigation, 5, 32, "NOTHING" );
ds_grid_set(global.navigation, 0, 33, "woodInteriorInventoryNeed" );
ds_grid_set(global.navigation, 1, 33, "NOTHING" );
ds_grid_set(global.navigation, 2, 33, "NOTHING" );
ds_grid_set(global.navigation, 3, 33, "NOTHING" );
ds_grid_set(global.navigation, 4, 33, "NOTHING" );
ds_grid_set(global.navigation, 5, 33, "NOTHING" );
ds_grid_set(global.navigation, 0, 34, "woodInteriorInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 34, "NOTHING" );
ds_grid_set(global.navigation, 2, 34, "NOTHING" );
ds_grid_set(global.navigation, 3, 34, "NOTHING" );
ds_grid_set(global.navigation, 4, 34, "NOTHING" );
ds_grid_set(global.navigation, 5, 34, "NOTHING" );
ds_grid_set(global.navigation, 0, 35, "woodInteriorInventoryDestroy" );
ds_grid_set(global.navigation, 1, 35, "NOTHING" );
ds_grid_set(global.navigation, 2, 35, "NOTHING" );
ds_grid_set(global.navigation, 3, 35, "NOTHING" );
ds_grid_set(global.navigation, 4, 35, "NOTHING" );
ds_grid_set(global.navigation, 5, 35, "NOTHING" );

//--woodExplore--//
ds_grid_set(global.navigation, 0, 36, "woodExploreChoices" );
ds_grid_set(global.navigation, 1, 36, "Leave the wood" );
ds_grid_set(global.navigation, 2, 36, "Go to the den" );
ds_grid_set(global.navigation, 3, 36, "NOTHING" );
ds_grid_set(global.navigation, 4, 36, "NOTHING" );
ds_grid_set(global.navigation, 5, 36, "NOTHING" );
ds_grid_set(global.navigation, 0, 37, "woodExploreTargets" );
ds_grid_set(global.navigation, 1, 37, "exterior" );
ds_grid_set(global.navigation, 2, 37, "woodDen" );
ds_grid_set(global.navigation, 3, 37, "NOTHING" );
ds_grid_set(global.navigation, 4, 37, "NOTHING" );
ds_grid_set(global.navigation, 5, 37, "NOTHING" );
ds_grid_set(global.navigation, 0, 38, "woodExploreInventoryGet" );
ds_grid_set(global.navigation, 1, 38, "NOTHING" );
ds_grid_set(global.navigation, 2, 38, "Dog Food" );
ds_grid_set(global.navigation, 3, 38, "NOTHING" );
ds_grid_set(global.navigation, 4, 38, "NOTHING" );
ds_grid_set(global.navigation, 5, 38, "NOTHING" );
ds_grid_set(global.navigation, 0, 39, "woodExploreInventoryNeed" );
ds_grid_set(global.navigation, 1, 39, "NOTHING" );
ds_grid_set(global.navigation, 2, 39, "NOTHING" );
ds_grid_set(global.navigation, 3, 39, "NOTHING" );
ds_grid_set(global.navigation, 4, 39, "NOTHING" );
ds_grid_set(global.navigation, 5, 39, "NOTHING" );
ds_grid_set(global.navigation, 0, 40, "woodExploreInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 40, "NOTHING" );
ds_grid_set(global.navigation, 2, 40, "NOTHING" );
ds_grid_set(global.navigation, 3, 40, "NOTHING" );
ds_grid_set(global.navigation, 4, 40, "NOTHING" );
ds_grid_set(global.navigation, 5, 40, "NOTHING" );
ds_grid_set(global.navigation, 0, 41, "woodExploreInventoryDestroy" );
ds_grid_set(global.navigation, 1, 41, "NOTHING" );
ds_grid_set(global.navigation, 2, 41, "NOTHING" );
ds_grid_set(global.navigation, 3, 41, "NOTHING" );
ds_grid_set(global.navigation, 4, 41, "NOTHING" );
ds_grid_set(global.navigation, 5, 41, "NOTHING" );

//--woodDen--//
ds_grid_set(global.navigation, 0, 42, "woodDenChoices" );
ds_grid_set(global.navigation, 1, 42, "Check out the shiny thing" );
ds_grid_set(global.navigation, 2, 42, "Explore the woods" );
ds_grid_set(global.navigation, 3, 42, "Leave the woods" );
ds_grid_set(global.navigation, 4, 42, "NOTHING" );
ds_grid_set(global.navigation, 5, 42, "NOTHING" );
ds_grid_set(global.navigation, 0, 43, "woodDenTargets" );
ds_grid_set(global.navigation, 1, 43, "woodCollar" );
ds_grid_set(global.navigation, 2, 43, "woodExplore" );
ds_grid_set(global.navigation, 3, 43, "exterior" );
ds_grid_set(global.navigation, 4, 43, "NOTHING" );
ds_grid_set(global.navigation, 5, 43, "NOTHING" );
ds_grid_set(global.navigation, 0, 44, "woodDenInventoryGet" );
ds_grid_set(global.navigation, 1, 44, "Collar" );
ds_grid_set(global.navigation, 2, 44, "Stick" );
ds_grid_set(global.navigation, 3, 44, "NOTHING" );
ds_grid_set(global.navigation, 4, 44, "NOTHING" );
ds_grid_set(global.navigation, 5, 44, "NOTHING" );
ds_grid_set(global.navigation, 0, 45, "woodDenInventoryNeed" );
ds_grid_set(global.navigation, 1, 45, "Open Dog Food" );
ds_grid_set(global.navigation, 2, 45, "NOTHING" );
ds_grid_set(global.navigation, 3, 45, "NOTHING" );
ds_grid_set(global.navigation, 4, 45, "NOTHING" );
ds_grid_set(global.navigation, 5, 45, "NOTHING" );
ds_grid_set(global.navigation, 0, 46, "woodDenInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 46, "missingOpenDogFood" );
ds_grid_set(global.navigation, 2, 46, "NOTHING" );
ds_grid_set(global.navigation, 3, 46, "NOTHING" );
ds_grid_set(global.navigation, 4, 46, "NOTHING" );
ds_grid_set(global.navigation, 5, 46, "NOTHING" );
ds_grid_set(global.navigation, 0, 47, "woodDenInventoryDestroy" );
ds_grid_set(global.navigation, 1, 47, "Open Dog Food" );
ds_grid_set(global.navigation, 2, 47, "NOTHING" );
ds_grid_set(global.navigation, 3, 47, "NOTHING" );
ds_grid_set(global.navigation, 4, 47, "NOTHING" );
ds_grid_set(global.navigation, 5, 47, "NOTHING" );

//--woodCollar--//
ds_grid_set(global.navigation, 0, 48, "woodCollarChoices" );
ds_grid_set(global.navigation, 1, 48, "Go to the den" );
ds_grid_set(global.navigation, 2, 48, "Explore the wood" );
ds_grid_set(global.navigation, 3, 48, "Leave the wood" );
ds_grid_set(global.navigation, 4, 48, "NOTHING" );
ds_grid_set(global.navigation, 5, 48, "NOTHING" );
ds_grid_set(global.navigation, 0, 49, "woodCollarTargets" );
ds_grid_set(global.navigation, 1, 49, "woodDen" );
ds_grid_set(global.navigation, 2, 49, "woodExplore" );
ds_grid_set(global.navigation, 3, 49, "exterior" );
ds_grid_set(global.navigation, 4, 49, "NOTHING" );
ds_grid_set(global.navigation, 5, 49, "NOTHING" );
ds_grid_set(global.navigation, 0, 50, "woodCollarInventoryGet" );
ds_grid_set(global.navigation, 1, 50, "Dog Food" );
ds_grid_set(global.navigation, 2, 50, "Stick" );
ds_grid_set(global.navigation, 3, 50, "NOTHING" );
ds_grid_set(global.navigation, 4, 50, "NOTHING" );
ds_grid_set(global.navigation, 5, 50, "NOTHING" );
ds_grid_set(global.navigation, 0, 51, "woodCollarInventoryNeed" );
ds_grid_set(global.navigation, 1, 51, "NOTHING" );
ds_grid_set(global.navigation, 2, 51, "NOTHING" );
ds_grid_set(global.navigation, 3, 51, "NOTHING" );
ds_grid_set(global.navigation, 4, 51, "NOTHING" );
ds_grid_set(global.navigation, 5, 51, "NOTHING" );
ds_grid_set(global.navigation, 0, 52, "woodCollarInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 52, "NOTHING" );
ds_grid_set(global.navigation, 2, 52, "NOTHING" );
ds_grid_set(global.navigation, 3, 52, "NOTHING" );
ds_grid_set(global.navigation, 4, 52, "NOTHING" );
ds_grid_set(global.navigation, 5, 52, "NOTHING" );
ds_grid_set(global.navigation, 0, 53, "woodCollarInventoryDestroy" );
ds_grid_set(global.navigation, 1, 53, "NOTHING" );
ds_grid_set(global.navigation, 2, 53, "NOTHING" );
ds_grid_set(global.navigation, 3, 53, "NOTHING" );
ds_grid_set(global.navigation, 4, 53, "NOTHING" );
ds_grid_set(global.navigation, 5, 53, "NOTHING" );

//--abandonedShopInterior--//
ds_grid_set(global.navigation, 0, 54, "abandonedShopInteriorChoices" );
ds_grid_set(global.navigation, 1, 54, "Take a look at the shelves" );
ds_grid_set(global.navigation, 2, 54, "Check out the counter" );
ds_grid_set(global.navigation, 3, 54, "NOTHING" );
ds_grid_set(global.navigation, 4, 54, "NOTHING" );
ds_grid_set(global.navigation, 5, 54, "NOTHING" );
ds_grid_set(global.navigation, 0, 55, "abandonedShopInteriorTargets" );
ds_grid_set(global.navigation, 1, 55, "abandonedShopShelves" );
ds_grid_set(global.navigation, 2, 55, "abandonedShopCounter" );
ds_grid_set(global.navigation, 3, 55, "NOTHING" );
ds_grid_set(global.navigation, 4, 55, "NOTHING" );
ds_grid_set(global.navigation, 5, 55, "NOTHING" );
ds_grid_set(global.navigation, 0, 56, "abandonedShopInteriorInventoryGet" );
ds_grid_set(global.navigation, 1, 56, "First Aid Kit" );
ds_grid_set(global.navigation, 2, 56, "NOTHING" );
ds_grid_set(global.navigation, 3, 56, "NOTHING" );
ds_grid_set(global.navigation, 4, 56, "NOTHING" );
ds_grid_set(global.navigation, 5, 56, "NOTHING" );
ds_grid_set(global.navigation, 0, 57, "abandonedShopInteriorInventoryNeed" );
ds_grid_set(global.navigation, 1, 57, "Stick" );
ds_grid_set(global.navigation, 2, 57, "NOTHING" );
ds_grid_set(global.navigation, 3, 57, "NOTHING" );
ds_grid_set(global.navigation, 4, 57, "NOTHING" );
ds_grid_set(global.navigation, 5, 57, "NOTHING" );
ds_grid_set(global.navigation, 0, 58, "abandonedShopInteriorInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 58, "missingStick" );
ds_grid_set(global.navigation, 2, 58, "NOTHING" );
ds_grid_set(global.navigation, 3, 58, "NOTHING" );
ds_grid_set(global.navigation, 4, 58, "NOTHING" );
ds_grid_set(global.navigation, 5, 58, "NOTHING" );
ds_grid_set(global.navigation, 0, 59, "abandonedShopInteriorInventoryDestroy" );
ds_grid_set(global.navigation, 1, 59, "Stick" );
ds_grid_set(global.navigation, 2, 59, "NOTHING" );
ds_grid_set(global.navigation, 3, 59, "NOTHING" );
ds_grid_set(global.navigation, 4, 59, "NOTHING" );
ds_grid_set(global.navigation, 5, 59, "NOTHING" );

//--missingOpenDogFood--//
ds_grid_set(global.navigation, 0, 60, "missingOpenDogFoodChoices" );
ds_grid_set(global.navigation, 1, 60, "Head over to the den" );
ds_grid_set(global.navigation, 2, 60, "Explore the wood" );
ds_grid_set(global.navigation, 3, 60, "Leave the wood" );
ds_grid_set(global.navigation, 4, 60, "NOTHING" );
ds_grid_set(global.navigation, 5, 60, "NOTHING" );
ds_grid_set(global.navigation, 0, 61, "missingOpenDogFoodTargets" );
ds_grid_set(global.navigation, 1, 61, "woodDen" );
ds_grid_set(global.navigation, 2, 61, "woodExplore" );
ds_grid_set(global.navigation, 3, 61, "exterior" );
ds_grid_set(global.navigation, 4, 61, "NOTHING" );
ds_grid_set(global.navigation, 5, 61, "NOTHING" );
ds_grid_set(global.navigation, 0, 62, "missingOpenDogFoodInventoryGet" );
ds_grid_set(global.navigation, 1, 62, "Dog Food" );
ds_grid_set(global.navigation, 2, 62, "Stick" );
ds_grid_set(global.navigation, 3, 62, "NOTHING" );
ds_grid_set(global.navigation, 4, 62, "NOTHING" );
ds_grid_set(global.navigation, 5, 62, "NOTHING" );
ds_grid_set(global.navigation, 0, 63, "missingOpenDogFoodInventoryNeed" );
ds_grid_set(global.navigation, 1, 63, "NOTHING" );
ds_grid_set(global.navigation, 2, 63, "NOTHING" );
ds_grid_set(global.navigation, 3, 63, "NOTHING" );
ds_grid_set(global.navigation, 4, 63, "NOTHING" );
ds_grid_set(global.navigation, 5, 63, "NOTHING" );
ds_grid_set(global.navigation, 0, 64, "missingOpenDogFoodInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 64, "NOTHING" );
ds_grid_set(global.navigation, 2, 64, "NOTHING" );
ds_grid_set(global.navigation, 3, 64, "NOTHING" );
ds_grid_set(global.navigation, 4, 64, "NOTHING" );
ds_grid_set(global.navigation, 5, 64, "NOTHING" );
ds_grid_set(global.navigation, 0, 65, "missingOpenDogFoodInventoryDestroy" );
ds_grid_set(global.navigation, 1, 65, "NOTHING" );
ds_grid_set(global.navigation, 2, 65, "NOTHING" );
ds_grid_set(global.navigation, 3, 65, "NOTHING" );
ds_grid_set(global.navigation, 4, 65, "NOTHING" );
ds_grid_set(global.navigation, 5, 65, "NOTHING" );



//-----------------------------------------------------------//
//------------------Abandoned Shop---------------------------//
//-----------------------------------------------------------//



//--missingDogFood--//
ds_grid_set(global.navigation, 0, 66, "missingDogFoodChoices" );
ds_grid_set(global.navigation, 1, 66, "Leave" );
ds_grid_set(global.navigation, 2, 66, "NOTHING" );
ds_grid_set(global.navigation, 3, 66, "NOTHING" );
ds_grid_set(global.navigation, 4, 66, "NOTHING" );
ds_grid_set(global.navigation, 5, 66, "NOTHING" );
ds_grid_set(global.navigation, 0, 67, "missingDogFoodTargets" );
ds_grid_set(global.navigation, 1, 67, "exterior" );
ds_grid_set(global.navigation, 2, 67, "NOTHING" );
ds_grid_set(global.navigation, 3, 67, "NOTHING" );
ds_grid_set(global.navigation, 4, 67, "NOTHING" );
ds_grid_set(global.navigation, 5, 67, "NOTHING" );
ds_grid_set(global.navigation, 0, 68, "missingDogFoodInventoryGet" );
ds_grid_set(global.navigation, 1, 68, "NOTHING" );
ds_grid_set(global.navigation, 2, 68, "NOTHING" );
ds_grid_set(global.navigation, 3, 68, "NOTHING" );
ds_grid_set(global.navigation, 4, 68, "NOTHING" );
ds_grid_set(global.navigation, 5, 68, "NOTHING" );
ds_grid_set(global.navigation, 0, 69, "missingDogFoodInventoryNeed" );
ds_grid_set(global.navigation, 1, 69, "NOTHING" );
ds_grid_set(global.navigation, 2, 69, "NOTHING" );
ds_grid_set(global.navigation, 3, 69, "NOTHING" );
ds_grid_set(global.navigation, 4, 69, "NOTHING" );
ds_grid_set(global.navigation, 5, 69, "NOTHING" );
ds_grid_set(global.navigation, 0, 70, "missingDogFoodInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 70, "NOTHING" );
ds_grid_set(global.navigation, 2, 70, "NOTHING" );
ds_grid_set(global.navigation, 3, 70, "NOTHING" );
ds_grid_set(global.navigation, 4, 70, "NOTHING" );
ds_grid_set(global.navigation, 5, 70, "NOTHING" );
ds_grid_set(global.navigation, 0, 71, "missingDogFoodInventoryDestroy" );
ds_grid_set(global.navigation, 1, 71, "NOTHING" );
ds_grid_set(global.navigation, 2, 71, "NOTHING" );
ds_grid_set(global.navigation, 3, 71, "NOTHING" );
ds_grid_set(global.navigation, 4, 71, "NOTHING" );
ds_grid_set(global.navigation, 5, 71, "NOTHING" );

//--missingCollar--//
ds_grid_set(global.navigation, 0, 72, "missingCollarChoices" );
ds_grid_set(global.navigation, 1, 72, "Leave" );
ds_grid_set(global.navigation, 2, 72, "NOTHING" );
ds_grid_set(global.navigation, 3, 72, "NOTHING" );
ds_grid_set(global.navigation, 4, 72, "NOTHING" );
ds_grid_set(global.navigation, 5, 72, "NOTHING" );
ds_grid_set(global.navigation, 0, 73, "missingCollarTargets" );
ds_grid_set(global.navigation, 1, 73, "exterior" );
ds_grid_set(global.navigation, 2, 73, "NOTHING" );
ds_grid_set(global.navigation, 3, 73, "NOTHING" );
ds_grid_set(global.navigation, 4, 73, "NOTHING" );
ds_grid_set(global.navigation, 5, 73, "NOTHING" );
ds_grid_set(global.navigation, 0, 74, "missingCollarInventoryGet" );
ds_grid_set(global.navigation, 1, 74, "NOTHING" );
ds_grid_set(global.navigation, 2, 74, "NOTHING" );
ds_grid_set(global.navigation, 3, 74, "NOTHING" );
ds_grid_set(global.navigation, 4, 74, "NOTHING" );
ds_grid_set(global.navigation, 5, 74, "NOTHING" );
ds_grid_set(global.navigation, 0, 75, "missingCollarInventoryNeed" );
ds_grid_set(global.navigation, 1, 75, "NOTHING" );
ds_grid_set(global.navigation, 2, 75, "NOTHING" );
ds_grid_set(global.navigation, 3, 75, "NOTHING" );
ds_grid_set(global.navigation, 4, 75, "NOTHING" );
ds_grid_set(global.navigation, 5, 75, "NOTHING" );
ds_grid_set(global.navigation, 0, 78, "missingCollarInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 78, "NOTHING" );
ds_grid_set(global.navigation, 2, 78, "NOTHING" );
ds_grid_set(global.navigation, 3, 78, "NOTHING" );
ds_grid_set(global.navigation, 4, 78, "NOTHING" );
ds_grid_set(global.navigation, 5, 78, "NOTHING" );
ds_grid_set(global.navigation, 0, 79, "missingCollarInventoryDestroy" );
ds_grid_set(global.navigation, 1, 79, "NOTHING" );
ds_grid_set(global.navigation, 2, 79, "NOTHING" );
ds_grid_set(global.navigation, 3, 79, "NOTHING" );
ds_grid_set(global.navigation, 4, 79, "NOTHING" );
ds_grid_set(global.navigation, 5, 79, "NOTHING" );


//--abandonedShopShelves--//
ds_grid_set(global.navigation, 0, 80, "abandonedShopShelvesChoices" );
ds_grid_set(global.navigation, 1, 80, "Check out the counter" );
ds_grid_set(global.navigation, 2, 80, "Leave" );
ds_grid_set(global.navigation, 3, 80, "NOTHING" );
ds_grid_set(global.navigation, 4, 80, "NOTHING" );
ds_grid_set(global.navigation, 5, 80, "NOTHING" );
ds_grid_set(global.navigation, 0, 81, "abandonedShopShelvesTargets" );
ds_grid_set(global.navigation, 1, 81, "abandonedShopCounter" );
ds_grid_set(global.navigation, 2, 81, "exterior" );
ds_grid_set(global.navigation, 3, 81, "NOTHING" );
ds_grid_set(global.navigation, 4, 81, "NOTHING" );
ds_grid_set(global.navigation, 5, 81, "NOTHING" );
ds_grid_set(global.navigation, 0, 82, "abandonedShopShelvesInventoryGet" );
ds_grid_set(global.navigation, 1, 82, "NOTHING" );
ds_grid_set(global.navigation, 2, 82, "NOTHING" );
ds_grid_set(global.navigation, 3, 82, "NOTHING" );
ds_grid_set(global.navigation, 4, 82, "NOTHING" );
ds_grid_set(global.navigation, 5, 82, "NOTHING" );
ds_grid_set(global.navigation, 0, 83, "abandonedShopShelvesInventoryNeed" );
ds_grid_set(global.navigation, 1, 83, "NOTHING" );
ds_grid_set(global.navigation, 2, 83, "NOTHING" );
ds_grid_set(global.navigation, 3, 83, "NOTHING" );
ds_grid_set(global.navigation, 4, 83, "NOTHING" );
ds_grid_set(global.navigation, 5, 83, "NOTHING" );
ds_grid_set(global.navigation, 0, 84, "abandonedShopShelvesInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 84, "NOTHING" );
ds_grid_set(global.navigation, 2, 84, "NOTHING" );
ds_grid_set(global.navigation, 3, 84, "NOTHING" );
ds_grid_set(global.navigation, 4, 84, "NOTHING" );
ds_grid_set(global.navigation, 5, 84, "NOTHING" );
ds_grid_set(global.navigation, 0, 85, "abandonedShopShelvesInventoryDestroy" );
ds_grid_set(global.navigation, 1, 85, "NOTHING" );
ds_grid_set(global.navigation, 2, 85, "NOTHING" );
ds_grid_set(global.navigation, 3, 85, "NOTHING" );
ds_grid_set(global.navigation, 4, 85, "NOTHING" );
ds_grid_set(global.navigation, 5, 85, "NOTHING" );

//--abandonedShopCounter--//
ds_grid_set(global.navigation, 0, 86, "abandonedShopCounterChoices" );
ds_grid_set(global.navigation, 1, 86, "Take a look at the shelves" );
ds_grid_set(global.navigation, 2, 86, "Leave" );
ds_grid_set(global.navigation, 3, 86, "NOTHING" );
ds_grid_set(global.navigation, 4, 86, "NOTHING" );
ds_grid_set(global.navigation, 5, 86, "NOTHING" );
ds_grid_set(global.navigation, 0, 87, "abandonedShopCounterTargets" );
ds_grid_set(global.navigation, 1, 87, "abandonedShopShelves" );
ds_grid_set(global.navigation, 2, 87, "exterior" );
ds_grid_set(global.navigation, 3, 87, "NOTHING" );
ds_grid_set(global.navigation, 4, 87, "NOTHING" );
ds_grid_set(global.navigation, 5, 87, "NOTHING" );
ds_grid_set(global.navigation, 0, 88, "abandonedShopCounterInventoryGet" );
ds_grid_set(global.navigation, 1, 88, "First Aid Kit" );
ds_grid_set(global.navigation, 2, 88, "NOTHING" );
ds_grid_set(global.navigation, 3, 88, "NOTHING" );
ds_grid_set(global.navigation, 4, 88, "NOTHING" );
ds_grid_set(global.navigation, 5, 88, "NOTHING" );
ds_grid_set(global.navigation, 0, 89, "abandonedShopCounterInventoryNeed" );
ds_grid_set(global.navigation, 1, 89, "Stick" );
ds_grid_set(global.navigation, 2, 89, "NOTHING" );
ds_grid_set(global.navigation, 3, 89, "NOTHING" );
ds_grid_set(global.navigation, 4, 89, "NOTHING" );
ds_grid_set(global.navigation, 5, 89, "NOTHING" );
ds_grid_set(global.navigation, 0, 90, "abandonedShopCounterInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 90, "missingStick" );
ds_grid_set(global.navigation, 2, 90, "NOTHING" );
ds_grid_set(global.navigation, 3, 90, "NOTHING" );
ds_grid_set(global.navigation, 4, 90, "NOTHING" );
ds_grid_set(global.navigation, 5, 90, "NOTHING" );
ds_grid_set(global.navigation, 0, 91, "abandonedShopCounterInventoryDestroy" );
ds_grid_set(global.navigation, 1, 91, "Stick" );
ds_grid_set(global.navigation, 2, 91, "NOTHING" );
ds_grid_set(global.navigation, 3, 91, "NOTHING" );
ds_grid_set(global.navigation, 4, 91, "NOTHING" );
ds_grid_set(global.navigation, 5, 91, "NOTHING" );

//--missingStick--//
ds_grid_set(global.navigation, 0, 92, "missingStickChoices" );
ds_grid_set(global.navigation, 1, 92, "Take a look at the counter" );
ds_grid_set(global.navigation, 2, 92, "Leave" );
ds_grid_set(global.navigation, 3, 92, "NOTHING" );
ds_grid_set(global.navigation, 4, 92, "NOTHING" );
ds_grid_set(global.navigation, 5, 92, "NOTHING" );
ds_grid_set(global.navigation, 0, 93, "missingStickTargets" );
ds_grid_set(global.navigation, 1, 93, "abandonedShopCounter" );
ds_grid_set(global.navigation, 2, 93, "exterior" );
ds_grid_set(global.navigation, 3, 93, "NOTHING" );
ds_grid_set(global.navigation, 4, 93, "NOTHING" );
ds_grid_set(global.navigation, 5, 93, "NOTHING" );
ds_grid_set(global.navigation, 0, 94, "missingStickInventoryGet" );
ds_grid_set(global.navigation, 1, 94, "NOTHING" );
ds_grid_set(global.navigation, 2, 94, "NOTHING" );
ds_grid_set(global.navigation, 3, 94, "NOTHING" );
ds_grid_set(global.navigation, 4, 94, "NOTHING" );
ds_grid_set(global.navigation, 5, 94, "NOTHING" );
ds_grid_set(global.navigation, 0, 95, "missingStickInventoryNeed" );
ds_grid_set(global.navigation, 1, 95, "NOTHING" );
ds_grid_set(global.navigation, 2, 95, "NOTHING" );
ds_grid_set(global.navigation, 3, 95, "NOTHING" );
ds_grid_set(global.navigation, 4, 95, "NOTHING" );
ds_grid_set(global.navigation, 5, 95, "NOTHING" );
ds_grid_set(global.navigation, 0, 96, "missingStickInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 96, "NOTHING" );
ds_grid_set(global.navigation, 2, 96, "NOTHING" );
ds_grid_set(global.navigation, 3, 96, "NOTHING" );
ds_grid_set(global.navigation, 4, 96, "NOTHING" );
ds_grid_set(global.navigation, 5, 96, "NOTHING" );
ds_grid_set(global.navigation, 0, 97, "missingStickInventoryDestroy" );
ds_grid_set(global.navigation, 1, 97, "NOTHING" );
ds_grid_set(global.navigation, 2, 97, "NOTHING" );
ds_grid_set(global.navigation, 3, 97, "NOTHING" );
ds_grid_set(global.navigation, 4, 97, "NOTHING" );
ds_grid_set(global.navigation, 5, 97, "NOTHING" );



//-----------------------------------------------------------//
//--------------------Empty House----------------------------//
//-----------------------------------------------------------//

//--emptyHouseBedroom--//
ds_grid_set(global.navigation, 0, 98, "emptyHouseBedroomChoices" );
ds_grid_set(global.navigation, 1, 98, "Take a look in the kitchen" );
ds_grid_set(global.navigation, 2, 98, "Head to the basement" );
ds_grid_set(global.navigation, 3, 98, "Leave" );
ds_grid_set(global.navigation, 4, 98, "NOTHING" );
ds_grid_set(global.navigation, 5, 98, "NOTHING" );
ds_grid_set(global.navigation, 0, 99, "emptyHouseBedroomTargets" );
ds_grid_set(global.navigation, 1, 99, "emptyHouseKitchen" );
ds_grid_set(global.navigation, 2, 99, "outro" );
ds_grid_set(global.navigation, 3, 99, "exterior" );
ds_grid_set(global.navigation, 4, 99, "NOTHING" );
ds_grid_set(global.navigation, 5, 99, "NOTHING" );
ds_grid_set(global.navigation, 0, 100, "emptyHouseBedroomInventoryGet" );
ds_grid_set(global.navigation, 1, 100, "NOTHING" );
ds_grid_set(global.navigation, 2, 100, "NOTHING" );
ds_grid_set(global.navigation, 3, 100, "NOTHING" );
ds_grid_set(global.navigation, 4, 100, "NOTHING" );
ds_grid_set(global.navigation, 5, 100, "NOTHING" );
ds_grid_set(global.navigation, 0, 101, "emptyHouseBedroomInventoryNeed" );
ds_grid_set(global.navigation, 1, 101, "NOTHING" );
ds_grid_set(global.navigation, 2, 101, "First Aid Kit" );
ds_grid_set(global.navigation, 3, 101, "NOTHING" );
ds_grid_set(global.navigation, 4, 101, "NOTHING" );
ds_grid_set(global.navigation, 5, 101, "NOTHING" );
ds_grid_set(global.navigation, 0, 102, "emptyHouseBedroomInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 102, "NOTHING" );
ds_grid_set(global.navigation, 2, 102, "missingAidKit" );
ds_grid_set(global.navigation, 3, 102, "NOTHING" );
ds_grid_set(global.navigation, 4, 102, "NOTHING" );
ds_grid_set(global.navigation, 5, 102, "NOTHING" );
ds_grid_set(global.navigation, 0, 103, "emptyHouseBedroomInventoryDestroy" );
ds_grid_set(global.navigation, 1, 103, "NOTHING" );
ds_grid_set(global.navigation, 2, 103, "First Aid Kit" );
ds_grid_set(global.navigation, 3, 103, "NOTHING" );
ds_grid_set(global.navigation, 4, 103, "NOTHING" );
ds_grid_set(global.navigation, 5, 103, "NOTHING" );

//--emptyHouseKitchen--//
ds_grid_set(global.navigation, 0, 104, "emptyHouseKitchenChoices" );
ds_grid_set(global.navigation, 1, 104, "Take a look in the bedroom" );
ds_grid_set(global.navigation, 2, 104, "Head to the basement" );
ds_grid_set(global.navigation, 3, 104, "Leave" );
ds_grid_set(global.navigation, 4, 104, "NOTHING" );
ds_grid_set(global.navigation, 5, 104, "NOTHING" );
ds_grid_set(global.navigation, 0, 105, "emptyHouseKitchenTargets" );
ds_grid_set(global.navigation, 1, 105, "emptyHouseBedroom" );
ds_grid_set(global.navigation, 2, 105, "outro" );
ds_grid_set(global.navigation, 3, 105, "exterior" );
ds_grid_set(global.navigation, 4, 105, "NOTHING" );
ds_grid_set(global.navigation, 5, 105, "NOTHING" );
ds_grid_set(global.navigation, 0, 106, "emptyHouseKitchenInventoryGet" );
ds_grid_set(global.navigation, 1, 106, "NOTHING" );
ds_grid_set(global.navigation, 2, 106, "NOTHING" );
ds_grid_set(global.navigation, 3, 106, "NOTHING" );
ds_grid_set(global.navigation, 4, 106, "NOTHING" );
ds_grid_set(global.navigation, 5, 106, "NOTHING" );
ds_grid_set(global.navigation, 0, 107, "emptyHouseKitchenInventoryNeed" );
ds_grid_set(global.navigation, 1, 107, "NOTHING" );
ds_grid_set(global.navigation, 2, 107, "First Aid Kit" );
ds_grid_set(global.navigation, 3, 107, "NOTHING" );
ds_grid_set(global.navigation, 4, 107, "NOTHING" );
ds_grid_set(global.navigation, 5, 107, "NOTHING" );
ds_grid_set(global.navigation, 0, 108, "emptyHouseKitchenInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 108, "NOTHING" );
ds_grid_set(global.navigation, 2, 108, "missingAidKit" );
ds_grid_set(global.navigation, 3, 108, "NOTHING" );
ds_grid_set(global.navigation, 4, 108, "NOTHING" );
ds_grid_set(global.navigation, 5, 108, "NOTHING" );
ds_grid_set(global.navigation, 0, 109, "emptyHouseKitchenInventoryDestroy" );
ds_grid_set(global.navigation, 1, 109, "NOTHING" );
ds_grid_set(global.navigation, 2, 109, "First Aid Kit" );
ds_grid_set(global.navigation, 3, 109, "NOTHING" );
ds_grid_set(global.navigation, 4, 109, "NOTHING" );
ds_grid_set(global.navigation, 5, 109, "NOTHING" );

//--emptyHouseBasement--//
ds_grid_set(global.navigation, 0, 110, "emptyHouseBasementChoices" );
ds_grid_set(global.navigation, 1, 110, "END" );
ds_grid_set(global.navigation, 2, 110, "NOTHING" );
ds_grid_set(global.navigation, 3, 110, "NOTHING" );
ds_grid_set(global.navigation, 4, 110, "NOTHING" );
ds_grid_set(global.navigation, 5, 110, "NOTHING" );
ds_grid_set(global.navigation, 0, 111, "emptyHouseBasementTargets" );
ds_grid_set(global.navigation, 1, 111, "outro" );
ds_grid_set(global.navigation, 2, 111, "NOTHING" );
ds_grid_set(global.navigation, 3, 111, "NOTHING" );
ds_grid_set(global.navigation, 4, 111, "NOTHING" );
ds_grid_set(global.navigation, 5, 111, "NOTHING" );
ds_grid_set(global.navigation, 0, 112, "emptyHouseBasementInventoryGet" );
ds_grid_set(global.navigation, 1, 112, "NOTHING" );
ds_grid_set(global.navigation, 2, 112, "NOTHING" );
ds_grid_set(global.navigation, 3, 112, "NOTHING" );
ds_grid_set(global.navigation, 4, 112, "NOTHING" );
ds_grid_set(global.navigation, 5, 112, "NOTHING" );
ds_grid_set(global.navigation, 0, 113, "emptyHouseBasementInventoryNeed" );
ds_grid_set(global.navigation, 1, 113, "NOTHING" );
ds_grid_set(global.navigation, 2, 113, "NOTHING" );
ds_grid_set(global.navigation, 3, 113, "NOTHING" );
ds_grid_set(global.navigation, 4, 113, "NOTHING" );
ds_grid_set(global.navigation, 5, 113, "NOTHING" );
ds_grid_set(global.navigation, 0, 114, "emptyHouseBasementInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 114, "NOTHING" );
ds_grid_set(global.navigation, 2, 114, "NOTHING" );
ds_grid_set(global.navigation, 3, 114, "NOTHING" );
ds_grid_set(global.navigation, 4, 114, "NOTHING" );
ds_grid_set(global.navigation, 5, 114, "NOTHING" );
ds_grid_set(global.navigation, 0, 115, "emptyHouseBasementInventoryDestroy" );
ds_grid_set(global.navigation, 1, 115, "NOTHING" );
ds_grid_set(global.navigation, 2, 115, "NOTHING" );
ds_grid_set(global.navigation, 3, 115, "NOTHING" );
ds_grid_set(global.navigation, 4, 115, "NOTHING" );
ds_grid_set(global.navigation, 5, 115, "NOTHING" );

//--missingAidKit--//
ds_grid_set(global.navigation, 0, 116, "missingAidKitChoices" );
ds_grid_set(global.navigation, 1, 116, "Head to the kitchen" );
ds_grid_set(global.navigation, 2, 116, "Take a look in the bedroom" );
ds_grid_set(global.navigation, 3, 116, "Leave" );
ds_grid_set(global.navigation, 4, 116, "NOTHING" );
ds_grid_set(global.navigation, 5, 116, "NOTHING" );
ds_grid_set(global.navigation, 0, 117, "missingAidKitTargets" );
ds_grid_set(global.navigation, 1, 117, "emptyHouseKitchen" );
ds_grid_set(global.navigation, 2, 117, "emptyHouseBedroom" );
ds_grid_set(global.navigation, 3, 117, "exterior" );
ds_grid_set(global.navigation, 4, 117, "NOTHING" );
ds_grid_set(global.navigation, 5, 117, "NOTHING" );
ds_grid_set(global.navigation, 0, 118, "missingAidKitInventoryGet" );
ds_grid_set(global.navigation, 1, 118, "NOTHING" );
ds_grid_set(global.navigation, 2, 118, "NOTHING" );
ds_grid_set(global.navigation, 3, 118, "NOTHING" );
ds_grid_set(global.navigation, 4, 118, "NOTHING" );
ds_grid_set(global.navigation, 5, 118, "NOTHING" );
ds_grid_set(global.navigation, 0, 119, "missingAidKitInventoryNeed" );
ds_grid_set(global.navigation, 1, 119, "NOTHING" );
ds_grid_set(global.navigation, 2, 119, "NOTHING" );
ds_grid_set(global.navigation, 3, 119, "NOTHING" );
ds_grid_set(global.navigation, 4, 119, "NOTHING" );
ds_grid_set(global.navigation, 5, 119, "NOTHING" );
ds_grid_set(global.navigation, 0, 120, "missingAidKitInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 120, "NOTHING" );
ds_grid_set(global.navigation, 2, 120, "NOTHING" );
ds_grid_set(global.navigation, 3, 120, "NOTHING" );
ds_grid_set(global.navigation, 4, 120, "NOTHING" );
ds_grid_set(global.navigation, 5, 120, "NOTHING" );
ds_grid_set(global.navigation, 0, 121, "missingAidKitInventoryDestroy" );
ds_grid_set(global.navigation, 1, 121, "NOTHING" );
ds_grid_set(global.navigation, 2, 121, "NOTHING" );
ds_grid_set(global.navigation, 3, 121, "NOTHING" );
ds_grid_set(global.navigation, 4, 121, "NOTHING" );
ds_grid_set(global.navigation, 5, 121, "NOTHING" );

//--yardInterior--//
ds_grid_set(global.navigation, 0, 122, "yardInteriorChoices" );
ds_grid_set(global.navigation, 1, 122, "Leave" );
ds_grid_set(global.navigation, 2, 122, "NOTHING" );
ds_grid_set(global.navigation, 3, 122, "NOTHING" );
ds_grid_set(global.navigation, 4, 122, "NOTHING" );
ds_grid_set(global.navigation, 5, 122, "NOTHING" );
ds_grid_set(global.navigation, 0, 123, "yardInteriorTargets" );
ds_grid_set(global.navigation, 1, 123, "exterior" );
ds_grid_set(global.navigation, 2, 123, "NOTHING" );
ds_grid_set(global.navigation, 3, 123, "NOTHING" );
ds_grid_set(global.navigation, 4, 123, "NOTHING" );
ds_grid_set(global.navigation, 5, 123, "NOTHING" );
ds_grid_set(global.navigation, 0, 124, "yardInteriorInventoryGet" );
ds_grid_set(global.navigation, 1, 124, "NOTHING" );
ds_grid_set(global.navigation, 2, 124, "NOTHING" );
ds_grid_set(global.navigation, 3, 124, "NOTHING" );
ds_grid_set(global.navigation, 4, 124, "NOTHING" );
ds_grid_set(global.navigation, 5, 124, "NOTHING" );
ds_grid_set(global.navigation, 0, 125, "yardInteriorInventoryNeed" );
ds_grid_set(global.navigation, 1, 125, "NOTHING" );
ds_grid_set(global.navigation, 2, 125, "NOTHING" );
ds_grid_set(global.navigation, 3, 125, "NOTHING" );
ds_grid_set(global.navigation, 4, 125, "NOTHING" );
ds_grid_set(global.navigation, 5, 125, "NOTHING" );
ds_grid_set(global.navigation, 0, 126, "yardInteriorInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 126, "NOTHING" );
ds_grid_set(global.navigation, 2, 126, "NOTHING" );
ds_grid_set(global.navigation, 3, 126, "NOTHING" );
ds_grid_set(global.navigation, 4, 126, "NOTHING" );
ds_grid_set(global.navigation, 5, 126, "NOTHING" );
ds_grid_set(global.navigation, 0, 127, "yardInteriorInventoryDestroy" );
ds_grid_set(global.navigation, 1, 127, "NOTHING" );
ds_grid_set(global.navigation, 2, 127, "NOTHING" );
ds_grid_set(global.navigation, 3, 127, "NOTHING" );
ds_grid_set(global.navigation, 4, 127, "NOTHING" );
ds_grid_set(global.navigation, 5, 127, "NOTHING" );

//--emptyHouseInterior--//
ds_grid_set(global.navigation, 0, 128, "emptyHouseInteriorChoices" );
ds_grid_set(global.navigation, 1, 128, "Take a look in the kitchen" );
ds_grid_set(global.navigation, 2, 128, "Check out the basement" );
ds_grid_set(global.navigation, 3, 128, "Head up to the bedroom" );
ds_grid_set(global.navigation, 4, 128, "NOTHING" );
ds_grid_set(global.navigation, 5, 128, "NOTHING" );
ds_grid_set(global.navigation, 0, 129, "emptyHouseInteriorTargets" );
ds_grid_set(global.navigation, 1, 129, "emptyHouseKitchen" );
ds_grid_set(global.navigation, 2, 129, "outro" );
ds_grid_set(global.navigation, 3, 129, "emptyHouseBedroom" );
ds_grid_set(global.navigation, 4, 129, "NOTHING" );
ds_grid_set(global.navigation, 5, 129, "NOTHING" );
ds_grid_set(global.navigation, 0, 130, "emptyHouseInteriorInventoryGet" );
ds_grid_set(global.navigation, 1, 130, "NOTHING" );
ds_grid_set(global.navigation, 2, 130, "NOTHING" );
ds_grid_set(global.navigation, 3, 130, "NOTHING" );
ds_grid_set(global.navigation, 4, 130, "NOTHING" );
ds_grid_set(global.navigation, 5, 130, "NOTHING" );
ds_grid_set(global.navigation, 0, 131, "emptyHouseInteriorInventoryNeed" );
ds_grid_set(global.navigation, 1, 131, "NOTHING" );
ds_grid_set(global.navigation, 2, 131, "First Aid Kit" );
ds_grid_set(global.navigation, 3, 131, "NOTHING" );
ds_grid_set(global.navigation, 4, 131, "NOTHING" );
ds_grid_set(global.navigation, 5, 131, "NOTHING" );
ds_grid_set(global.navigation, 0, 132, "emptyHouseInteriorInventoryMissingTarget" );
ds_grid_set(global.navigation, 1, 132, "NOTHING" );
ds_grid_set(global.navigation, 2, 132, "missingAidKit" );
ds_grid_set(global.navigation, 3, 132, "NOTHING" );
ds_grid_set(global.navigation, 4, 132, "NOTHING" );
ds_grid_set(global.navigation, 5, 132, "NOTHING" );
ds_grid_set(global.navigation, 0, 133, "emptyHouseInteriorInventoryDestroy" );
ds_grid_set(global.navigation, 1, 133, "NOTHING" );
ds_grid_set(global.navigation, 2, 133, "First Aid Kit" );
ds_grid_set(global.navigation, 3, 133, "NOTHING" );
ds_grid_set(global.navigation, 4, 133, "NOTHING" );
ds_grid_set(global.navigation, 5, 133, "NOTHING" );

